import os
import secrets
import sqlite3
from datetime import datetime, timezone

from flask import g
from werkzeug.security import generate_password_hash

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None

INTEGRITY_ERRORS = (sqlite3.IntegrityError,)

if psycopg is not None:
    INTEGRITY_ERRORS = INTEGRITY_ERRORS + (psycopg.IntegrityError,)


def database_path():
    configured_path = os.environ.get("DATABASE_PATH")

    if configured_path:
        return configured_path

    return os.path.join(os.path.dirname(__file__), "instance", "deltasigma.sqlite3")


def database_url():
    return os.environ.get("DATABASE_URL")


def database_engine():
    return "postgres" if database_url() else "sqlite"


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def normalize_email(email):
    return str(email or "").strip().lower()


def generate_temporary_password(length=14):
    return secrets.token_urlsafe(length)[:length]


def db_bool(value):
    if database_engine() == "postgres":
        return bool(value)

    return 1 if bool(value) else 0


def get_db():
    if "db" not in g:
        if database_engine() == "postgres":
            if psycopg is None:
                raise RuntimeError("Brakuje pakietu psycopg wymaganego do połączenia z Neon Postgres.")

            g.db = psycopg.connect(database_url(), row_factory=dict_row)
        else:
            path = database_path()
            os.makedirs(os.path.dirname(path), exist_ok=True)

            connection = sqlite3.connect(path)
            connection.row_factory = sqlite3.Row
            g.db = connection

    return g.db


def prepare_sql(sql):
    if database_engine() == "postgres":
        return sql.replace("?", "%s")

    return sql


def execute(sql, values=()):
    return get_db().execute(prepare_sql(sql), values)


def close_db(_error=None):
    connection = g.pop("db", None)

    if connection is not None:
        connection.close()


def register_auth_db(app):
    app.teardown_appcontext(close_db)


def row_to_dict(row):
    if row is None:
        return None

    return dict(row)


def init_auth_db():
    db = get_db()

    if database_engine() == "postgres":
        statements = [
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                display_name TEXT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('admin', 'student')),
                level TEXT,
                password_hash TEXT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TEXT NOT NULL,
                last_login_at TEXT
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS task_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                task_id TEXT NOT NULL,
                source_id TEXT,
                file TEXT,
                level TEXT,
                topic TEXT,
                difficulty INTEGER,
                result TEXT NOT NULL CHECK(result IN ('good', 'medium', 'bad')),
                hint_used BOOLEAN NOT NULL DEFAULT FALSE,
                answer_shown BOOLEAN NOT NULL DEFAULT FALSE,
                task_mode TEXT,
                created_at TEXT NOT NULL
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_task_progress_user_id
                ON task_progress(user_id)
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_task_progress_task_id
                ON task_progress(task_id)
            """,
        ]

        for statement in statements:
            db.execute(statement)
    else:
        db.executescript(
            """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL,
            role TEXT NOT NULL CHECK(role IN ('admin', 'student')),
            level TEXT,
            password_hash TEXT NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            last_login_at TEXT
        );

        CREATE TABLE IF NOT EXISTS task_progress (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            task_id TEXT NOT NULL,
            source_id TEXT,
            file TEXT,
            level TEXT,
            topic TEXT,
            difficulty INTEGER,
            result TEXT NOT NULL CHECK(result IN ('good', 'medium', 'bad')),
            hint_used INTEGER NOT NULL DEFAULT 0,
            answer_shown INTEGER NOT NULL DEFAULT 0,
            task_mode TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_task_progress_user_id
            ON task_progress(user_id);

        CREATE INDEX IF NOT EXISTS idx_task_progress_task_id
            ON task_progress(task_id);
        """
        )

    db.commit()


def public_user(row):
    user = row_to_dict(row)

    if not user:
        return None

    user.pop("password_hash", None)
    user["is_active"] = bool(user["is_active"])

    return user


def get_user_by_email(email):
    return row_to_dict(execute("SELECT * FROM users WHERE email = ?", (normalize_email(email),)).fetchone())


def get_user_by_id(user_id):
    return row_to_dict(execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone())


def create_user(email, display_name, password, role="student", level="matura_podstawowa", is_active=True):
    normalized_email = normalize_email(email)
    created_at = now_iso()
    db = get_db()

    db.execute(
        prepare_sql(
            """
            INSERT INTO users (email, display_name, role, level, password_hash, is_active, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """
        ),
        (
            normalized_email,
            str(display_name or normalized_email).strip(),
            role,
            level,
            generate_password_hash(password),
            db_bool(is_active),
            created_at,
        ),
    )
    db.commit()

    return get_user_by_email(normalized_email)


def ensure_admin_user(email, password):
    existing = get_user_by_email(email)

    if existing:
        return existing, False

    return create_user(
        email=email,
        display_name="Administrator",
        password=password,
        role="admin",
        level=None,
        is_active=True,
    ), True


def sync_admin_user(email, password=None):
    existing = get_user_by_email(email)

    if not existing:
        return ensure_admin_user(email, password or generate_temporary_password())

    assignments = [
        "display_name = ?",
        "role = ?",
        "level = ?",
        "is_active = ?",
    ]
    values = [
        existing.get("display_name") or "Administrator",
        "admin",
        None,
        db_bool(True),
    ]

    if password:
        assignments.append("password_hash = ?")
        values.append(generate_password_hash(password))

    values.append(existing["id"])
    db = get_db()
    db.execute(
        prepare_sql(f"UPDATE users SET {', '.join(assignments)} WHERE id = ?"),
        values,
    )
    db.commit()

    return get_user_by_id(existing["id"]), False


def touch_last_login(user_id):
    db = get_db()

    db.execute(
        prepare_sql("UPDATE users SET last_login_at = ? WHERE id = ?"),
        (now_iso(), user_id),
    )
    db.commit()


def list_students():
    rows = execute(
        """
        SELECT
            u.id,
            u.email,
            u.display_name,
            u.role,
            u.level,
            u.is_active,
            u.created_at,
            u.last_login_at,
            COUNT(p.id) AS attempts,
            COALESCE(SUM(CASE WHEN p.result = 'good' THEN 1 ELSE 0 END), 0) AS good_count,
            COALESCE(SUM(CASE WHEN p.result = 'medium' THEN 1 ELSE 0 END), 0) AS medium_count,
            COALESCE(SUM(CASE WHEN p.result = 'bad' THEN 1 ELSE 0 END), 0) AS bad_count,
            MAX(p.created_at) AS last_activity_at
        FROM users u
        LEFT JOIN task_progress p ON p.user_id = u.id
        WHERE u.role = 'student'
        GROUP BY u.id, u.email, u.display_name, u.role, u.level, u.is_active, u.created_at, u.last_login_at
        ORDER BY u.created_at DESC
        """,
    ).fetchall()

    students = []

    for row in rows:
        student = dict(row)
        student["is_active"] = bool(student["is_active"])
        student["accuracy"] = round((student["good_count"] / student["attempts"]) * 100, 1) if student["attempts"] else 0
        students.append(student)

    return students


def update_student(user_id, fields):
    allowed = {
        "display_name": "display_name",
        "level": "level",
        "is_active": "is_active",
    }
    assignments = []
    values = []

    for key, column in allowed.items():
        if key not in fields:
            continue

        value = fields[key]

        if key == "is_active":
            value = db_bool(value)

        assignments.append(f"{column} = ?")
        values.append(value)

    if not assignments:
        return row_to_dict(
            execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
        )

    values.append(user_id)
    db = get_db()
    cursor = db.execute(
        prepare_sql(f"UPDATE users SET {', '.join(assignments)} WHERE id = ? AND role = 'student'"),
        values,
    )
    db.commit()

    if cursor.rowcount == 0:
        return None

    return row_to_dict(
        execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
    )


def reset_user_password(user_id, password):
    db = get_db()

    cursor = db.execute(
        prepare_sql("UPDATE users SET password_hash = ? WHERE id = ? AND role = 'student'"),
        (generate_password_hash(password), user_id),
    )
    db.commit()

    if cursor.rowcount == 0:
        return None

    return row_to_dict(
        execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
    )


def delete_student(user_id):
    existing = row_to_dict(
        execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
    )

    if not existing:
        return None

    db = get_db()
    db.execute(prepare_sql("DELETE FROM task_progress WHERE user_id = ?"), (user_id,))
    db.execute(prepare_sql("DELETE FROM users WHERE id = ? AND role = 'student'"), (user_id,))
    db.commit()

    return existing


def record_progress(user_id, data):
    created_at = now_iso()
    db = get_db()

    values = (
        user_id,
        data["task_id"],
        data.get("source_id"),
        data.get("file"),
        data.get("level"),
        data.get("topic"),
        data.get("difficulty"),
        data["result"],
        db_bool(data.get("hint_used")),
        db_bool(data.get("answer_shown")),
        data.get("task_mode"),
        created_at,
    )

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                INSERT INTO task_progress (
                    user_id,
                    task_id,
                    source_id,
                    file,
                    level,
                    topic,
                    difficulty,
                    result,
                    hint_used,
                    answer_shown,
                    task_mode,
                    created_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING *
                """
            ),
            values,
        )
        progress = row_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            INSERT INTO task_progress (
                user_id,
                task_id,
                source_id,
                file,
                level,
                topic,
                difficulty,
                result,
                hint_used,
                answer_shown,
                task_mode,
                created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            values,
        )
        progress = row_to_dict(
            db.execute(
                "SELECT * FROM task_progress WHERE id = ?",
                (cursor.lastrowid,),
            ).fetchone()
        )

    db.commit()

    return progress


def progress_for_user(user_id, limit=200):
    return [
        dict(row)
        for row in execute(
            """
            SELECT *
            FROM task_progress
            WHERE user_id = ?
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (user_id, limit),
        )
        .fetchall()
    ]
