import os
import secrets
import sqlite3
import hashlib
from datetime import datetime, timedelta, timezone

from flask import g
from werkzeug.security import generate_password_hash

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None

INTEGRITY_ERRORS = (sqlite3.IntegrityError,)

if psycopg is not None:
    INTEGRITY_ERRORS = INTEGRITY_ERRORS + (psycopg.IntegrityError,)


def database_path():
    configured_path = os.environ.get("DATABASE_PATH")

    if configured_path:
        return configured_path

    return os.path.join(os.path.dirname(__file__), "instance", "deltasigma.sqlite3")


def database_url():
    return os.environ.get("DATABASE_URL")


def database_engine():
    return "postgres" if database_url() else "sqlite"


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def normalize_email(email):
    return str(email or "").strip().lower()


def generate_temporary_password(length=14):
    return secrets.token_urlsafe(length)[:length]


def generate_parent_access_token():
    return secrets.token_urlsafe(32)


def hash_parent_access_token(token):
    return hashlib.sha256(str(token or "").encode("utf-8")).hexdigest()


def db_bool(value):
    if database_engine() == "postgres":
        return bool(value)

    return 1 if bool(value) else 0


def duration_seconds(value):
    try:
        seconds = int(value or 0)
    except (TypeError, ValueError):
        seconds = 0

    return max(0, min(seconds, 4 * 60 * 60))


def bounded_int(value, minimum=0, maximum=100000):
    try:
        number = int(value or 0)
    except (TypeError, ValueError):
        number = minimum

    return max(minimum, min(number, maximum))


def bounded_float(value, minimum=0.0, maximum=100000.0):
    try:
        number = float(value or 0)
    except (TypeError, ValueError):
        number = minimum

    return max(minimum, min(number, maximum))


def point_value(value):
    if value is None or value == "":
        return None

    try:
        points = float(value)
    except (TypeError, ValueError):
        return None

    if points < 0:
        return 0.0

    return round(points, 2)


def get_db():
    if "db" not in g:
        if database_engine() == "postgres":
            if psycopg is None:
                raise RuntimeError("Brakuje pakietu psycopg wymaganego do połączenia z Neon Postgres.")

            g.db = psycopg.connect(database_url(), row_factory=dict_row)
        else:
            path = database_path()
            os.makedirs(os.path.dirname(path), exist_ok=True)

            connection = sqlite3.connect(path)
            connection.row_factory = sqlite3.Row
            g.db = connection

    return g.db


def prepare_sql(sql):
    if database_engine() == "postgres":
        return sql.replace("?", "%s")

    return sql


def execute(sql, values=()):
    return get_db().execute(prepare_sql(sql), values)


def close_db(_error=None):
    connection = g.pop("db", None)

    if connection is not None:
        connection.close()


def register_auth_db(app):
    app.teardown_appcontext(close_db)


def row_to_dict(row):
    if row is None:
        return None

    return dict(row)


def review_item_to_dict(row):
    item = row_to_dict(row)

    if item:
        item["is_resolved"] = bool(item["is_resolved"])

    return item


def init_auth_db():
    db = get_db()

    if database_engine() == "postgres":
        statements = [
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                display_name TEXT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('admin', 'student')),
                level TEXT,
                password_hash TEXT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TEXT NOT NULL,
                last_login_at TEXT
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS task_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                task_id TEXT NOT NULL,
                source_id TEXT,
                file TEXT,
                level TEXT,
                topic TEXT,
                difficulty INTEGER,
                result TEXT NOT NULL CHECK(result IN ('good', 'medium', 'bad')),
                hint_used BOOLEAN NOT NULL DEFAULT FALSE,
                answer_shown BOOLEAN NOT NULL DEFAULT FALSE,
                task_mode TEXT,
                duration_seconds INTEGER NOT NULL DEFAULT 0,
                earned_points DOUBLE PRECISION,
                max_points DOUBLE PRECISION,
                created_at TEXT NOT NULL
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_task_progress_user_id
                ON task_progress(user_id)
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_task_progress_task_id
                ON task_progress(task_id)
            """,
            """
            CREATE TABLE IF NOT EXISTS speed_training_results (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                level TEXT NOT NULL,
                topic TEXT NOT NULL,
                difficulty TEXT NOT NULL,
                round_seconds INTEGER NOT NULL,
                correct_count INTEGER NOT NULL,
                mistake_count INTEGER NOT NULL,
                best_streak INTEGER NOT NULL,
                average_time_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_speed_training_results_user_id
                ON speed_training_results(user_id)
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_speed_training_results_scope
                ON speed_training_results(level, topic, difficulty, round_seconds)
            """,
            """
            CREATE TABLE IF NOT EXISTS parent_access_tokens (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                label TEXT,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TEXT NOT NULL,
                last_used_at TEXT,
                revoked_at TEXT
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_parent_access_tokens_user_id
                ON parent_access_tokens(user_id)
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_parent_access_tokens_token_hash
                ON parent_access_tokens(token_hash)
            """,
            """
            CREATE TABLE IF NOT EXISTS task_review_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                task_id TEXT NOT NULL,
                source_id TEXT,
                file TEXT,
                level TEXT,
                topic TEXT,
                difficulty INTEGER,
                title TEXT,
                course_part TEXT,
                note TEXT,
                is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TEXT NOT NULL,
                resolved_at TEXT
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_task_review_items_user_id
                ON task_review_items(user_id)
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_task_review_items_task_id
                ON task_review_items(task_id)
            """,
            """
            CREATE TABLE IF NOT EXISTS contact_messages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                contact TEXT NOT NULL,
                preferred_term TEXT,
                message TEXT NOT NULL,
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TEXT NOT NULL,
                read_at TEXT,
                deleted_at TEXT
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at
                ON contact_messages(created_at)
            """,
            """
            ALTER TABLE task_progress
                ADD COLUMN IF NOT EXISTS duration_seconds INTEGER NOT NULL DEFAULT 0
            """,
            """
            ALTER TABLE task_progress
                ADD COLUMN IF NOT EXISTS earned_points DOUBLE PRECISION
            """,
            """
            ALTER TABLE task_progress
                ADD COLUMN IF NOT EXISTS max_points DOUBLE PRECISION
            """,
            """
            ALTER TABLE contact_messages
                ADD COLUMN IF NOT EXISTS deleted_at TEXT
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_contact_messages_deleted_at
                ON contact_messages(deleted_at)
            """,
        ]

        for statement in statements:
            db.execute(statement)
    else:
        db.executescript(
            """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL,
            role TEXT NOT NULL CHECK(role IN ('admin', 'student')),
            level TEXT,
            password_hash TEXT NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            last_login_at TEXT
        );

        CREATE TABLE IF NOT EXISTS task_progress (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            task_id TEXT NOT NULL,
            source_id TEXT,
            file TEXT,
            level TEXT,
            topic TEXT,
            difficulty INTEGER,
            result TEXT NOT NULL CHECK(result IN ('good', 'medium', 'bad')),
            hint_used INTEGER NOT NULL DEFAULT 0,
            answer_shown INTEGER NOT NULL DEFAULT 0,
            task_mode TEXT,
            duration_seconds INTEGER NOT NULL DEFAULT 0,
            earned_points REAL,
            max_points REAL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_task_progress_user_id
            ON task_progress(user_id);

        CREATE INDEX IF NOT EXISTS idx_task_progress_task_id
            ON task_progress(task_id);

        CREATE TABLE IF NOT EXISTS speed_training_results (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            level TEXT NOT NULL,
            topic TEXT NOT NULL,
            difficulty TEXT NOT NULL,
            round_seconds INTEGER NOT NULL,
            correct_count INTEGER NOT NULL,
            mistake_count INTEGER NOT NULL,
            best_streak INTEGER NOT NULL,
            average_time_seconds REAL NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_speed_training_results_user_id
            ON speed_training_results(user_id);

        CREATE INDEX IF NOT EXISTS idx_speed_training_results_scope
            ON speed_training_results(level, topic, difficulty, round_seconds);

        CREATE TABLE IF NOT EXISTS parent_access_tokens (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            token_hash TEXT NOT NULL UNIQUE,
            label TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            last_used_at TEXT,
            revoked_at TEXT,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_parent_access_tokens_user_id
            ON parent_access_tokens(user_id);

        CREATE INDEX IF NOT EXISTS idx_parent_access_tokens_token_hash
            ON parent_access_tokens(token_hash);

        CREATE TABLE IF NOT EXISTS task_review_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            task_id TEXT NOT NULL,
            source_id TEXT,
            file TEXT,
            level TEXT,
            topic TEXT,
            difficulty INTEGER,
            title TEXT,
            course_part TEXT,
            note TEXT,
            is_resolved INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            resolved_at TEXT,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_task_review_items_user_id
            ON task_review_items(user_id);

        CREATE INDEX IF NOT EXISTS idx_task_review_items_task_id
            ON task_review_items(task_id);

        CREATE TABLE IF NOT EXISTS contact_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            contact TEXT NOT NULL,
            preferred_term TEXT,
            message TEXT NOT NULL,
            is_read INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            read_at TEXT,
            deleted_at TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at
            ON contact_messages(created_at);
        """
        )

        columns = {
            row["name"]
            for row in db.execute("PRAGMA table_info(task_progress)").fetchall()
        }

        if "duration_seconds" not in columns:
            db.execute("ALTER TABLE task_progress ADD COLUMN duration_seconds INTEGER NOT NULL DEFAULT 0")

        if "earned_points" not in columns:
            db.execute("ALTER TABLE task_progress ADD COLUMN earned_points REAL")

        if "max_points" not in columns:
            db.execute("ALTER TABLE task_progress ADD COLUMN max_points REAL")

        contact_columns = {
            row["name"]
            for row in db.execute("PRAGMA table_info(contact_messages)").fetchall()
        }

        if "deleted_at" not in contact_columns:
            db.execute("ALTER TABLE contact_messages ADD COLUMN deleted_at TEXT")

        db.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_contact_messages_deleted_at
                ON contact_messages(deleted_at)
            """
        )

    db.commit()


def public_user(row):
    user = row_to_dict(row)

    if not user:
        return None

    user.pop("password_hash", None)
    user["is_active"] = bool(user["is_active"])

    return user


def parent_access_to_dict(row):
    item = row_to_dict(row)

    if item:
        item["is_active"] = bool(item["is_active"])

    return item


def get_user_by_email(email):
    return row_to_dict(execute("SELECT * FROM users WHERE email = ?", (normalize_email(email),)).fetchone())


def get_user_by_id(user_id):
    return row_to_dict(execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone())


def create_user(email, display_name, password, role="student", level="matura_podstawowa", is_active=True):
    normalized_email = normalize_email(email)
    created_at = now_iso()
    db = get_db()

    db.execute(
        prepare_sql(
            """
            INSERT INTO users (email, display_name, role, level, password_hash, is_active, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """
        ),
        (
            normalized_email,
            str(display_name or normalized_email).strip(),
            role,
            level,
            generate_password_hash(password),
            db_bool(is_active),
            created_at,
        ),
    )
    db.commit()

    return get_user_by_email(normalized_email)


def ensure_admin_user(email, password):
    existing = get_user_by_email(email)

    if existing:
        return existing, False

    return create_user(
        email=email,
        display_name="Administrator",
        password=password,
        role="admin",
        level=None,
        is_active=True,
    ), True


def sync_admin_user(email, password=None):
    existing = get_user_by_email(email)

    if not existing:
        return ensure_admin_user(email, password or generate_temporary_password())

    assignments = [
        "display_name = ?",
        "role = ?",
        "level = ?",
        "is_active = ?",
    ]
    values = [
        existing.get("display_name") or "Administrator",
        "admin",
        None,
        db_bool(True),
    ]

    if password:
        assignments.append("password_hash = ?")
        values.append(generate_password_hash(password))

    values.append(existing["id"])
    db = get_db()
    db.execute(
        prepare_sql(f"UPDATE users SET {', '.join(assignments)} WHERE id = ?"),
        values,
    )
    db.commit()

    return get_user_by_id(existing["id"]), False


def touch_last_login(user_id):
    db = get_db()

    db.execute(
        prepare_sql("UPDATE users SET last_login_at = ? WHERE id = ?"),
        (now_iso(), user_id),
    )
    db.commit()


def list_students():
    rows = execute(
        """
        SELECT
            u.id,
            u.email,
            u.display_name,
            u.role,
            u.level,
            u.is_active,
            u.created_at,
            u.last_login_at,
            COUNT(p.id) AS attempts,
            COALESCE(SUM(CASE WHEN p.result = 'good' THEN 1 ELSE 0 END), 0) AS good_count,
            COALESCE(SUM(CASE WHEN p.result = 'medium' THEN 1 ELSE 0 END), 0) AS medium_count,
            COALESCE(SUM(CASE WHEN p.result = 'bad' THEN 1 ELSE 0 END), 0) AS bad_count,
            COALESCE(SUM(COALESCE(p.duration_seconds, 0)), 0) AS total_duration_seconds,
            COALESCE(r.review_count, 0) AS review_count,
            MAX(p.created_at) AS last_activity_at
        FROM users u
        LEFT JOIN task_progress p ON p.user_id = u.id
        LEFT JOIN (
            SELECT user_id, COUNT(*) AS review_count
            FROM task_review_items
            WHERE is_resolved = ?
            GROUP BY user_id
        ) r ON r.user_id = u.id
        WHERE u.role = 'student'
        GROUP BY u.id, u.email, u.display_name, u.role, u.level, u.is_active, u.created_at, u.last_login_at, r.review_count
        ORDER BY u.created_at DESC
        """,
        (db_bool(False),),
    ).fetchall()

    students = []

    for row in rows:
        student = dict(row)
        student["is_active"] = bool(student["is_active"])
        student["accuracy"] = round((student["good_count"] / student["attempts"]) * 100, 1) if student["attempts"] else 0
        student["average_duration_seconds"] = round(student["total_duration_seconds"] / student["attempts"]) if student["attempts"] else 0
        students.append(student)

    return students


def update_student(user_id, fields):
    allowed = {
        "display_name": "display_name",
        "level": "level",
        "is_active": "is_active",
    }
    assignments = []
    values = []

    for key, column in allowed.items():
        if key not in fields:
            continue

        value = fields[key]

        if key == "is_active":
            value = db_bool(value)

        assignments.append(f"{column} = ?")
        values.append(value)

    if not assignments:
        return row_to_dict(
            execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
        )

    values.append(user_id)
    db = get_db()
    cursor = db.execute(
        prepare_sql(f"UPDATE users SET {', '.join(assignments)} WHERE id = ? AND role = 'student'"),
        values,
    )
    db.commit()

    if cursor.rowcount == 0:
        return None

    return row_to_dict(
        execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
    )


def reset_user_password(user_id, password):
    db = get_db()

    cursor = db.execute(
        prepare_sql("UPDATE users SET password_hash = ? WHERE id = ? AND role = 'student'"),
        (generate_password_hash(password), user_id),
    )
    db.commit()

    if cursor.rowcount == 0:
        return None

    return row_to_dict(
        execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
    )


def delete_student(user_id):
    existing = row_to_dict(
        execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
    )

    if not existing:
        return None

    db = get_db()
    db.execute(prepare_sql("DELETE FROM parent_access_tokens WHERE user_id = ?"), (user_id,))
    db.execute(prepare_sql("DELETE FROM task_review_items WHERE user_id = ?"), (user_id,))
    db.execute(prepare_sql("DELETE FROM task_progress WHERE user_id = ?"), (user_id,))
    db.execute(prepare_sql("DELETE FROM speed_training_results WHERE user_id = ?"), (user_id,))
    db.execute(prepare_sql("DELETE FROM users WHERE id = ? AND role = 'student'"), (user_id,))
    db.commit()

    return existing


def create_parent_access_token(user_id, label="Rodzic"):
    student = row_to_dict(
        execute("SELECT * FROM users WHERE id = ? AND role = 'student'", (user_id,)).fetchone()
    )

    if not student:
        return None, None

    token = generate_parent_access_token()
    created_at = now_iso()
    db = get_db()

    db.execute(
        prepare_sql(
            """
            UPDATE parent_access_tokens
            SET is_active = ?, revoked_at = ?
            WHERE user_id = ? AND is_active = ?
            """
        ),
        (db_bool(False), created_at, user_id, db_bool(True)),
    )

    values = (
        user_id,
        hash_parent_access_token(token),
        str(label or "Rodzic").strip()[:120],
        db_bool(True),
        created_at,
    )

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                INSERT INTO parent_access_tokens (
                    user_id,
                    token_hash,
                    label,
                    is_active,
                    created_at
                )
                VALUES (?, ?, ?, ?, ?)
                RETURNING *
                """
            ),
            values,
        )
        item = parent_access_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            INSERT INTO parent_access_tokens (
                user_id,
                token_hash,
                label,
                is_active,
                created_at
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            values,
        )
        item = parent_access_to_dict(
            db.execute(
                "SELECT * FROM parent_access_tokens WHERE id = ?",
                (cursor.lastrowid,),
            ).fetchone()
        )

    db.commit()

    return item, token


def disable_parent_access_token(user_id):
    revoked_at = now_iso()
    db = get_db()
    cursor = db.execute(
        prepare_sql(
            """
            UPDATE parent_access_tokens
            SET is_active = ?, revoked_at = ?
            WHERE user_id = ? AND is_active = ?
            """
        ),
        (db_bool(False), revoked_at, user_id, db_bool(True)),
    )
    db.commit()

    return cursor.rowcount > 0


def parent_access_by_token(token):
    token_hash = hash_parent_access_token(token)
    row = execute(
        """
        SELECT
            p.id AS access_id,
            p.user_id AS access_user_id,
            p.label AS access_label,
            p.is_active AS access_is_active,
            p.created_at AS access_created_at,
            p.last_used_at AS access_last_used_at,
            p.revoked_at AS access_revoked_at,
            u.id AS student_id,
            u.email AS student_email,
            u.display_name AS student_display_name,
            u.role AS student_role,
            u.level AS student_level,
            u.is_active AS student_is_active,
            u.created_at AS student_created_at,
            u.last_login_at AS student_last_login_at
        FROM parent_access_tokens p
        JOIN users u ON u.id = p.user_id
        WHERE p.token_hash = ?
            AND p.is_active = ?
            AND u.role = 'student'
        LIMIT 1
        """,
        (token_hash, db_bool(True)),
    ).fetchone()

    if not row:
        return None

    item = dict(row)
    student = {
        "id": item["student_id"],
        "email": item["student_email"],
        "display_name": item["student_display_name"],
        "role": item["student_role"],
        "level": item["student_level"],
        "is_active": bool(item["student_is_active"]),
        "created_at": item["student_created_at"],
        "last_login_at": item["student_last_login_at"],
    }
    access = {
        "id": item["access_id"],
        "user_id": item["access_user_id"],
        "label": item["access_label"],
        "is_active": bool(item["access_is_active"]),
        "created_at": item["access_created_at"],
        "last_used_at": item["access_last_used_at"],
        "revoked_at": item["access_revoked_at"],
    }

    return {
        "access": access,
        "student": student,
    }


def touch_parent_access(access_id):
    db = get_db()

    db.execute(
        prepare_sql("UPDATE parent_access_tokens SET last_used_at = ? WHERE id = ?"),
        (now_iso(), access_id),
    )
    db.commit()


def record_progress(user_id, data):
    created_at = now_iso()
    db = get_db()
    max_points = point_value(data.get("max_points"))
    earned_points = point_value(data.get("earned_points"))

    if max_points is not None and earned_points is not None:
        earned_points = min(earned_points, max_points)

    values = (
        user_id,
        data["task_id"],
        data.get("source_id"),
        data.get("file"),
        data.get("level"),
        data.get("topic"),
        data.get("difficulty"),
        data["result"],
        db_bool(data.get("hint_used")),
        db_bool(data.get("answer_shown")),
        data.get("task_mode"),
        duration_seconds(data.get("duration_seconds")),
        earned_points,
        max_points,
        created_at,
    )

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                INSERT INTO task_progress (
                    user_id,
                    task_id,
                    source_id,
                    file,
                    level,
                    topic,
                    difficulty,
                    result,
                    hint_used,
                    answer_shown,
                    task_mode,
                    duration_seconds,
                    earned_points,
                    max_points,
                    created_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING *
                """
            ),
            values,
        )
        progress = row_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            INSERT INTO task_progress (
                user_id,
                task_id,
                source_id,
                file,
                level,
                topic,
                difficulty,
                result,
                hint_used,
                answer_shown,
                task_mode,
                duration_seconds,
                earned_points,
                max_points,
                created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            values,
        )
        progress = row_to_dict(
            db.execute(
                "SELECT * FROM task_progress WHERE id = ?",
                (cursor.lastrowid,),
            ).fetchone()
        )

    db.commit()

    return progress


def progress_for_user(user_id, limit=2000):
    return [
        dict(row)
        for row in execute(
            """
            SELECT *
            FROM task_progress
            WHERE user_id = ?
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (user_id, limit),
        )
        .fetchall()
    ]


def speed_training_result_to_dict(row, viewer_user_id=None):
    item = row_to_dict(row)

    if not item:
        return None

    for key in ("id", "user_id", "round_seconds", "correct_count", "mistake_count", "best_streak"):
        if key in item and item[key] is not None:
            item[key] = int(item[key])

    if "average_time_seconds" in item and item["average_time_seconds"] is not None:
        item["average_time_seconds"] = round(float(item["average_time_seconds"]), 3)

    if "student_is_active" in item:
        item["student_is_active"] = bool(item["student_is_active"])

    if viewer_user_id is not None:
        item["is_current_user"] = item.get("user_id") == viewer_user_id

    item.pop("user_id", None)

    return item


def record_speed_training_result(user_id, data):
    created_at = now_iso()
    values = (
        user_id,
        str(data.get("level") or "eo").strip()[:40],
        str(data.get("topic") or "all").strip()[:80],
        str(data.get("difficulty") or "1").strip()[:16],
        duration_seconds(data.get("round_seconds")),
        bounded_int(data.get("correct_count"), 0, 10000),
        bounded_int(data.get("mistake_count"), 0, 10000),
        bounded_int(data.get("best_streak"), 0, 10000),
        round(bounded_float(data.get("average_time_seconds"), 0, 3600), 3),
        created_at,
    )
    db = get_db()

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                INSERT INTO speed_training_results (
                    user_id,
                    level,
                    topic,
                    difficulty,
                    round_seconds,
                    correct_count,
                    mistake_count,
                    best_streak,
                    average_time_seconds,
                    created_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING *
                """
            ),
            values,
        )
        result = speed_training_result_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            INSERT INTO speed_training_results (
                user_id,
                level,
                topic,
                difficulty,
                round_seconds,
                correct_count,
                mistake_count,
                best_streak,
                average_time_seconds,
                created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            values,
        )
        result = speed_training_result_to_dict(
            db.execute(
                "SELECT * FROM speed_training_results WHERE id = ?",
                (cursor.lastrowid,),
            ).fetchone()
        )

    db.commit()

    return result


def speed_training_leaderboard(filters=None, limit=10, viewer_user_id=None):
    filters = filters or {}
    where = ["u.role = 'student'", "u.is_active = ?"]
    values = [db_bool(True)]
    filter_columns = {
        "level": "r.level",
        "topic": "r.topic",
        "difficulty": "r.difficulty",
        "round_seconds": "r.round_seconds",
    }

    for key, column in filter_columns.items():
        value = filters.get(key)

        if value in (None, ""):
            continue

        if key == "round_seconds":
            value = duration_seconds(value)

        where.append(f"{column} = ?")
        values.append(value)

    period = str(filters.get("period") or "").strip().lower()

    if period in {"week", "weekly"}:
        week_start = datetime.now(timezone.utc) - timedelta(days=7)

        where.append("r.created_at >= ?")
        values.append(week_start.isoformat())

    values.append(bounded_int(limit, 1, 50))
    rows = execute(
        f"""
        WITH ranked AS (
            SELECT
                r.id,
                r.user_id,
                u.display_name,
                u.level AS student_level,
                u.is_active AS student_is_active,
                r.level,
                r.topic,
                r.difficulty,
                r.round_seconds,
                r.correct_count,
                r.mistake_count,
                r.best_streak,
                r.average_time_seconds,
                r.created_at,
                ROW_NUMBER() OVER (
                    PARTITION BY r.user_id
                    ORDER BY
                        r.correct_count DESC,
                        r.mistake_count ASC,
                        r.average_time_seconds ASC,
                        r.best_streak DESC,
                        r.created_at DESC
                ) AS row_rank
            FROM speed_training_results r
            JOIN users u ON u.id = r.user_id
            WHERE {" AND ".join(where)}
        )
        SELECT *
        FROM ranked
        WHERE row_rank = 1
        ORDER BY
            correct_count DESC,
            mistake_count ASC,
            average_time_seconds ASC,
            best_streak DESC,
            created_at DESC
        LIMIT ?
        """,
        tuple(values),
    ).fetchall()

    leaderboard = []

    for index, row in enumerate(rows, start=1):
        item = speed_training_result_to_dict(row, viewer_user_id=viewer_user_id)
        item["rank"] = index
        item.pop("row_rank", None)
        leaderboard.append(item)

    return leaderboard


def speed_training_history(user_id, filters=None, limit=12):
    filters = filters or {}
    where = ["user_id = ?"]
    values = [user_id]
    filter_columns = {
        "level": "level",
        "topic": "topic",
        "difficulty": "difficulty",
        "round_seconds": "round_seconds",
    }

    for key, column in filter_columns.items():
        value = filters.get(key)

        if value in (None, ""):
            continue

        if key == "round_seconds":
            value = duration_seconds(value)

        where.append(f"{column} = ?")
        values.append(value)

    period = str(filters.get("period") or "").strip().lower()

    if period in {"week", "weekly"}:
        week_start = datetime.now(timezone.utc) - timedelta(days=7)

        where.append("created_at >= ?")
        values.append(week_start.isoformat())

    values.append(bounded_int(limit, 1, 40))
    rows = execute(
        f"""
        SELECT *
        FROM (
            SELECT *
            FROM speed_training_results
            WHERE {" AND ".join(where)}
            ORDER BY created_at DESC
            LIMIT ?
        ) AS recent
        ORDER BY created_at ASC
        """,
        tuple(values),
    ).fetchall()

    return [speed_training_result_to_dict(row) for row in rows]


def mark_task_for_review(user_id, data):
    existing = execute(
        """
        SELECT *
        FROM task_review_items
        WHERE user_id = ?
            AND task_id = ?
            AND is_resolved = ?
        ORDER BY created_at DESC
        LIMIT 1
        """,
        (user_id, data["task_id"], db_bool(False)),
    ).fetchone()

    if existing:
        return review_item_to_dict(existing), False

    created_at = now_iso()
    db = get_db()
    values = (
        user_id,
        data["task_id"],
        data.get("source_id"),
        data.get("file"),
        data.get("level"),
        data.get("topic"),
        data.get("difficulty"),
        data.get("title"),
        data.get("course_part"),
        data.get("note"),
        db_bool(False),
        created_at,
    )

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                INSERT INTO task_review_items (
                    user_id,
                    task_id,
                    source_id,
                    file,
                    level,
                    topic,
                    difficulty,
                    title,
                    course_part,
                    note,
                    is_resolved,
                    created_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING *
                """
            ),
            values,
        )
        item = review_item_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            INSERT INTO task_review_items (
                user_id,
                task_id,
                source_id,
                file,
                level,
                topic,
                difficulty,
                title,
                course_part,
                note,
                is_resolved,
                created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            values,
        )
        item = review_item_to_dict(
            db.execute(
                "SELECT * FROM task_review_items WHERE id = ?",
                (cursor.lastrowid,),
            ).fetchone()
        )

    db.commit()

    return item, True


def review_tasks_for_user(user_id, include_resolved=False):
    if include_resolved:
        rows = execute(
            """
            SELECT *
            FROM task_review_items
            WHERE user_id = ?
            ORDER BY is_resolved ASC, created_at DESC
            """,
            (user_id,),
        ).fetchall()
    else:
        rows = execute(
            """
            SELECT *
            FROM task_review_items
            WHERE user_id = ?
                AND is_resolved = ?
            ORDER BY created_at DESC
            """,
            (user_id, db_bool(False)),
        ).fetchall()

    return [review_item_to_dict(row) for row in rows]


def contact_message_to_dict(row):
    item = row_to_dict(row)

    if item:
        item["is_read"] = bool(item["is_read"])
        item["is_deleted"] = bool(item.get("deleted_at"))

    return item


def create_contact_message(data):
    contact = str(data.get("contact") or "").strip()
    preferred_term = str(data.get("preferred_term") or "").strip()
    message = str(data.get("message") or "").strip()

    if not contact or not message:
        raise ValueError("Kontakt i treść wiadomości są wymagane.")

    contact = contact[:254]
    preferred_term = preferred_term[:160] or None
    message = message[:3000]
    created_at = now_iso()
    db = get_db()
    values = (
        contact,
        preferred_term,
        message,
        db_bool(False),
        created_at,
    )

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                INSERT INTO contact_messages (
                    contact,
                    preferred_term,
                    message,
                    is_read,
                    created_at
                )
                VALUES (?, ?, ?, ?, ?)
                RETURNING *
                """
            ),
            values,
        )
        item = contact_message_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            INSERT INTO contact_messages (
                contact,
                preferred_term,
                message,
                is_read,
                created_at
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            values,
        )
        item = contact_message_to_dict(
            db.execute(
                "SELECT * FROM contact_messages WHERE id = ?",
                (cursor.lastrowid,),
            ).fetchone()
        )

    db.commit()

    return item


def list_contact_messages(limit=200, box="inbox"):
    show_trash = box == "trash"
    where_clause = "deleted_at IS NOT NULL" if show_trash else "deleted_at IS NULL"
    order_clause = "deleted_at DESC, created_at DESC" if show_trash else "is_read ASC, created_at DESC"

    return [
        contact_message_to_dict(row)
        for row in execute(
            f"""
            SELECT *
            FROM contact_messages
            WHERE {where_clause}
            ORDER BY {order_clause}
            LIMIT ?
            """,
            (limit,),
        )
        .fetchall()
    ]


def contact_message_counts():
    row = execute(
        """
        SELECT
            SUM(CASE WHEN deleted_at IS NULL THEN 1 ELSE 0 END) AS inbox,
            SUM(CASE WHEN deleted_at IS NOT NULL THEN 1 ELSE 0 END) AS trash,
            SUM(CASE WHEN deleted_at IS NULL AND is_read = ? THEN 1 ELSE 0 END) AS unread
        FROM contact_messages
        """,
        (db_bool(False),),
    ).fetchone()

    if row is None:
        return {
            "inbox": 0,
            "trash": 0,
            "unread": 0,
        }

    return {
        "inbox": int(row["inbox"] or 0),
        "trash": int(row["trash"] or 0),
        "unread": int(row["unread"] or 0),
    }


def update_contact_message_read_state(message_id, is_read=True):
    read_at = now_iso() if is_read else None
    db = get_db()

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                UPDATE contact_messages
                SET is_read = ?, read_at = ?
                WHERE id = ?
                RETURNING *
                """
            ),
            (db_bool(is_read), read_at, message_id),
        )
        item = contact_message_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            UPDATE contact_messages
            SET is_read = ?, read_at = ?
            WHERE id = ?
            """,
            (db_bool(is_read), read_at, message_id),
        )

        if cursor.rowcount == 0:
            item = None
        else:
            item = contact_message_to_dict(
                db.execute(
                    "SELECT * FROM contact_messages WHERE id = ?",
                    (message_id,),
                ).fetchone()
            )

    db.commit()

    return item


def update_contact_message_deleted_state(message_id, is_deleted=True):
    deleted_at = now_iso() if is_deleted else None
    db = get_db()

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                UPDATE contact_messages
                SET deleted_at = ?
                WHERE id = ?
                RETURNING *
                """
            ),
            (deleted_at, message_id),
        )
        item = contact_message_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            UPDATE contact_messages
            SET deleted_at = ?
            WHERE id = ?
            """,
            (deleted_at, message_id),
        )

        if cursor.rowcount == 0:
            item = None
        else:
            item = contact_message_to_dict(
                db.execute(
                    "SELECT * FROM contact_messages WHERE id = ?",
                    (message_id,),
                ).fetchone()
            )

    db.commit()

    return item


def delete_contact_message(message_id):
    db = get_db()
    item = contact_message_to_dict(
        execute(
            "SELECT * FROM contact_messages WHERE id = ?",
            (message_id,),
        ).fetchone()
    )

    if not item:
        return None

    db.execute(
        prepare_sql("DELETE FROM contact_messages WHERE id = ?"),
        (message_id,),
    )
    db.commit()

    return item


def update_review_task_resolution(item_id, is_resolved=True):
    resolved_at = now_iso() if is_resolved else None
    db = get_db()

    if database_engine() == "postgres":
        cursor = db.execute(
            prepare_sql(
                """
                UPDATE task_review_items
                SET is_resolved = ?, resolved_at = ?
                WHERE id = ?
                RETURNING *
                """
            ),
            (db_bool(is_resolved), resolved_at, item_id),
        )
        item = review_item_to_dict(cursor.fetchone())
    else:
        cursor = db.execute(
            """
            UPDATE task_review_items
            SET is_resolved = ?, resolved_at = ?
            WHERE id = ?
            """,
            (db_bool(is_resolved), resolved_at, item_id),
        )

        if cursor.rowcount == 0:
            item = None
        else:
            item = review_item_to_dict(
                db.execute(
                    "SELECT * FROM task_review_items WHERE id = ?",
                    (item_id,),
                ).fetchone()
            )

    db.commit()

    return item
